global:
  resolve_timeout: 5m

route:
  group_by: [alertname, severity, silo_id]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: slack-default
  routes:
    - match:
        severity: critical
      receiver: slack-critical

receivers:
  - name: slack-default
    slack_configs:
      - api_url_file: /etc/alertmanager/secrets/slack_webhook
        channel: '#agrisense-alerts'
        title: 'AgriSense Alert'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          {{ range .Alerts }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        send_resolved: true

  - name: slack-critical
    slack_configs:
      - api_url_file: /etc/alertmanager/secrets/slack_webhook
        channel: '#agrisense-critical'
        title: '🚨 CRITICAL ALERT - AgriSense'
        text: |
          *URGENT:* {{ .GroupLabels.alertname }}
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ end }}
        send_resolved: true

