global:
  resolve_timeout: 5m

route:
  receiver: 'null-receiver'
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'null-receiver'

