global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  # Self-scrape
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Simulator metrics
  - job_name: 'agrisense-simulator'
    scrape_interval: 10s
    static_configs:
      - targets: ['device-simulator:8081']

