groups:
  - name: sanity
    rules:
      - alert: Watchdog
        expr: vector(1)
        labels:
          severity: info
        annotations:
          summary: "Watchdog"
          description: "Always-firing alert to verify Prometheus→Alertmanager wiring."

      - alert: PrometheusTargetMissing
        expr: up == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Target missing"
          description: "Instance {{ $labels.instance }} is down."
